---
- name: debug playbook
  hosts: os-all
  tasks:
  - name: Show tmp variables
    debug:
      msg: "{{ ansible_facts | dict2items }}"
  #- name: Show interfaces details
  #  debug:
  #    msg: "{{ lookup('vars', 'ansible_' + item) }}"
  #  loop: "{{ ansible_interfaces }}"
  - name: set fact - bond interfaces (all LAN interfaces).
    set_fact:
      bond_interfaces: "{{ ansible_facts | dict2items | map(attribute='value')
      | selectattr('type', 'defined')  
      | selectattr('type', 'equalto', 'ether')  
      | selectattr('module', 'defined')  
      | rejectattr('module', 'match', 'iwl.*') 
      | rejectattr('module', 'match', 'cdc.*') 
      | map(attribute='device')
      | list }}" 
      # Convert KV dict ansible_facts to list of objects with K,V attributes, put all V in a list.
      # Filter the list for items with type defined. Without this type is evaluated even if not defined.
      # Filter the list for items with type = ether.
      # Filter out item with module = iwl*. (wifi iface).
      # Filter out item with module = cdc*. (wwan iface).
      # Create a list from attribute device.
      # Generate the final list.
