- hosts: k8s-all
  become: yes
  tasks:
   - name: install APT Transport HTTPS
     apt:
       name: "{{item}}"
       state: present
     loop:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common

   - name: add Docker GPG key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
   - name: Work out the distribution
     command: lsb_release -sc
     register: result
   - name: add Docker' APT repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
      state: present
      filename: 'docker.io'
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true


