---
- name: setup root key on ansible control host
  hosts: ansible-controller
  tasks:
    - name: copy root keys locally.
      become: true
      copy: 
        src: ../../util/ssh/{{ item }}
        dest: /root/.ssh/{{ item }}
        owner: root
        mode: 0600
      delegate_to: localhost
      with_items:
        - id_rsa
        - id_rsa.pub

- hosts: os-all
  become: true
  tasks:
    - name: make direcotry
      file:
        path: "/root/.ssh"
        state: directory
    - name: copy root keys
      copy: 
        src: ../../util/ssh/{{ item }}
        dest: /root/.ssh/{{ item }}
        owner: root
        mode: 0600
      with_items:
        - id_rsa
        - id_rsa.pub
    - name: set auth-keys.
      authorized_key: # copy local pubkey to remote host.
        user: root
        key: "{{ lookup('file', item) }}"
        state: present
      with_fileglob: "/root/.ssh/*.pub"
